# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LightsaberService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LightsaberService.proto',
  package='Lightsaber',
  syntax='proto3',
  serialized_options=b'\252\002\024Lightsaber.Contracts',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17LightsaberService.proto\x12\nLightsaber\"(\n\x13SubscriptionRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\"n\n\x14SubscriptionResponse\x12\x13\n\x0bspecVersion\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x17\n\x0f\x64\x61tacontenttype\x18\x05 \x01(\t2\xd1\x01\n\x11LightsaberService\x12Y\n\x10SubscribeSession\x12\x1f.Lightsaber.SubscriptionRequest\x1a .Lightsaber.SubscriptionResponse\"\x00\x30\x01\x12\x61\n\x18TerminalSubscribeSession\x12\x1f.Lightsaber.SubscriptionRequest\x1a .Lightsaber.SubscriptionResponse\"\x00\x30\x01\x42\x17\xaa\x02\x14Lightsaber.Contractsb\x06proto3'
)




_SUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='SubscriptionRequest',
  full_name='Lightsaber.SubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='Lightsaber.SubscriptionRequest.sessionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=79,
)


_SUBSCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='SubscriptionResponse',
  full_name='Lightsaber.SubscriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='specVersion', full_name='Lightsaber.SubscriptionResponse.specVersion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='Lightsaber.SubscriptionResponse.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='Lightsaber.SubscriptionResponse.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='Lightsaber.SubscriptionResponse.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datacontenttype', full_name='Lightsaber.SubscriptionResponse.datacontenttype', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['SubscriptionRequest'] = _SUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['SubscriptionResponse'] = _SUBSCRIPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscriptionRequest = _reflection.GeneratedProtocolMessageType('SubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONREQUEST,
  '__module__' : 'LightsaberService_pb2'
  # @@protoc_insertion_point(class_scope:Lightsaber.SubscriptionRequest)
  })
_sym_db.RegisterMessage(SubscriptionRequest)

SubscriptionResponse = _reflection.GeneratedProtocolMessageType('SubscriptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONRESPONSE,
  '__module__' : 'LightsaberService_pb2'
  # @@protoc_insertion_point(class_scope:Lightsaber.SubscriptionResponse)
  })
_sym_db.RegisterMessage(SubscriptionResponse)


DESCRIPTOR._options = None

_LIGHTSABERSERVICE = _descriptor.ServiceDescriptor(
  name='LightsaberService',
  full_name='Lightsaber.LightsaberService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=194,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeSession',
    full_name='Lightsaber.LightsaberService.SubscribeSession',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_SUBSCRIPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TerminalSubscribeSession',
    full_name='Lightsaber.LightsaberService.TerminalSubscribeSession',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_SUBSCRIPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIGHTSABERSERVICE)

DESCRIPTOR.services_by_name['LightsaberService'] = _LIGHTSABERSERVICE

# @@protoc_insertion_point(module_scope)
